www:
  build: .
  volumes:
    - "src:/usr/src/app/src"
    - "test:/usr/src/app/test"
  ports:
    - "8080"
  environment:
    - NODE_ENV
    - ALLOW_ORIGINS
    - AWS_ACCESS_KEY_ID
    - AWS_BUCKET_NAME
    - AWS_BUCKET_PATH
    - AWS_BUCKET_REGION
    - AWS_SECRET_ACCESS_KEY
    - LIBRATO_PREFIX
    - LIBRATO_TOKEN
    - LIBRATO_USER
    - SENTRY_DNS
  restart: always
