dev:
  image: starefossen/iojs-imagemagick:2-6
  working_dir: /usr/src/app
  volumes:
    - ".:/usr/src/app"
  command: npm run watch
  ports:
    - "8080"
  env_file: .env
  environment:
    - NODE_ENV=development
    - ALLOW_ORIGINS=example1.com,example2.com
    - VIRTUAL_HOST=proxy.turbasen.privat
    - VIRTUAL_PORT=8080
